### PR TITLE
Working vagrant-docker image with flask

### PR DESCRIPTION
**Pull request by sadam0930**
Copied from pet api demo

### CODE REVIEW

**Review by 0x932b — APPROVED** [review]
Looks good to me +1

**Comment by 0x932b** [comment]
Hi steve I am a bit confused, this is a possible duplicate with #1 is it?
Or the pull request is supposely a seperate issue from the origin?

**Comment by sadam0930** [comment]
The push request looks like it creates a new issue, which I linked with the
issue we created manually. I'll have to look up more commands on git to see
if there's a better way to consolidate.

**Comment by 0x932b** [comment]
Yep my bad, I just realized that's the default way of doing it
I am using this https://github.com/github/hub for the issue to pull-request conversions from cmd.
It's a handy feature but seemingly a hotly debated one and could be deprecated in the future
https://github.com/github/hub/commit/4f70dd126f46dec14fc341c97c18efae417743c7

**Pull request merged**
