### PR TITLE
Add an Action onClick and demo page.

### PR DESCRIPTION
**Pull request by 0x932b**

### CODE REVIEW

**Review by sadam0930 — COMMENTED** [review]
Currently when you click an item in the demo, you get redirected to /recommendations/{id}. It would be a better user experience if the current page were refreshed.

**Review by sadam0930 — CHANGES_REQUESTED** [review]
I tried running this locally and now nothing happens when I click on one of the cells.

**Comment by sadam0930** [comment]
@u932b Can you, please create a new pull request for your demo and commit the API for /recommendations/{id}/clicked for issue #29 ? The demo is technically not part of the scope of this sprint.

**Comment by 0x932b** [comment]
Closed for new merge request.

**Pull request closed without merging**
